const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.wrap,
		C3.Plugins.Spritefont2,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Fade,
		C3.Plugins.Function,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Function.Acts.SetReturnValue,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.Touch.Exps.AbsoluteXForID,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Touch.Exps.AbsoluteYForID,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Audio: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Browser: 0},
	{BtnMoreGames: 0},
	{BtnMusic: 0},
	{BtnSound: 0},
	{Wrap: 0},
	{Background1: 0},
	{BtnPlay: 0},
	{BtnInfo: 0},
	{LoadingFont: 0},
	{BtnRestart: 0},
	{BtnPause: 0},
	{ScoreFont: 0},
	{HighScoreFont: 0},
	{LastScoreFont: 0},
	{TimeFont: 0},
	{BoundToLayout: 0},
	{"8Direction": 0},
	{Solid: 0},
	{DragDrop: 0},
	{Player: 0},
	{Enemy3: 0},
	{Enemy2: 0},
	{Enemy1: 0},
	{Collision: 0},
	{CoinBox: 0},
	{Fade: 0},
	{Score100: 0},
	{Score125: 0},
	{Function: 0},
	{PlayerCollision: 0},
	{Background2: 0},
	{Frame: 0},
	{Sine: 0},
	{AddFuel: 0},
	{AddLife: 0},
	{barfuel: 0},
	{barlife: 0},
	{BarBackground: 0},
	{LifeBarLine: 0},
	{FuelBarLIne: 0},
	{Bullet: 0},
	{Enemy4: 0},
	{Enemy5: 0},
	{bartime: 0},
	{Background: 0},
	{barscore: 0},
	{GameLogo: 0},
	{Enemy6: 0},
	{Particles: 0},
	{Enemy7: 0},
	{ExplosionGround: 0},
	{rightcontrol: 0},
	{leftcontrol: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{MouseOver: 0},
	{ButtonsSound: 0},
	{Paused: 0},
	{Pause: 0},
	{Score: 0},
	{Life: 0},
	{Fuel: 0},
	{Seconds: 0},
	{Minutes: 0},
	{HighScore: 0},
	{LastScore: 0},
	{DeadZone: 0},
	{Music: 0},
	{Sound: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	BtnMoreGames: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	Background1: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	Player: class extends self.ISpriteInstance {},
	Enemy3: class extends self.ISpriteInstance {},
	Enemy2: class extends self.ISpriteInstance {},
	Enemy1: class extends self.ISpriteInstance {},
	Collision: class extends self.ISpriteInstance {},
	CoinBox: class extends self.ISpriteInstance {},
	Score100: class extends self.ISpriteInstance {},
	Score125: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	Background2: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	AddFuel: class extends self.ISpriteInstance {},
	AddLife: class extends self.ISpriteInstance {},
	barfuel: class extends self.ISpriteInstance {},
	barlife: class extends self.ISpriteInstance {},
	BarBackground: class extends self.ISpriteInstance {},
	LifeBarLine: class extends self.ISpriteInstance {},
	FuelBarLIne: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Enemy4: class extends self.ISpriteInstance {},
	Enemy5: class extends self.ISpriteInstance {},
	bartime: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	barscore: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	Enemy6: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Enemy7: class extends self.ISpriteInstance {},
	ExplosionGround: class extends self.ISpriteInstance {},
	rightcontrol: class extends self.ISpriteInstance {},
	leftcontrol: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	MouseOver: class extends self.ISpriteInstance {},
	ButtonsSound: class extends self.ISpriteInstance {}
}